name: Bounties
version: ${project.version}
main: me.kaotich00.bounties.Bounties
api-version: 1.16
authors: [Kaotich00]
description: A bounty plugin for Spigot 1.16.5
depend: [Vault]
softdepend: [Towny]
loadafter: [Vault]
commands:
  bounty:
    description: Main Bounties command
    usage: /<command>
    aliases: [bounty]

permissions:
  bounty.reload:
    description: Reload configuration file
    default: op
  bounty.modify:
    description: Modify player bounty
    default: op
  bounty.check:
    description: Check player bounty
    default: true
